version: '3.9'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: territory-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: territory
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: territory-redis
    restart: always
    ports:
      - "6379:6379"